INSERT INTO [dbo].[Songs] ([Title], [Artist], [Active])
VALUES
    ('In The Air Tonight', 'Original / Hybrid', 1),
    ('Young & Crazy', 'Frankie Ballard', 1),
    ('Barefoot Blue Jean Night', 'Jake Owen', 1),
    ('Whiskey Girl', 'Original', 1),
    ('One Day', 'Matisyahu', 1),
    ('Wagon Wheel', 'Darius Rucker', 1),
    ('Lovesong', 'Big Blue Hearts', 1),
    ('Skipping Rocks', 'Original', 1),
    ('1000 Faces', 'Randy Montana', 1),
    ('Wicked Game', 'Chris Isaak', 1),
    ('Southern Girl', 'Tim McGraw', 1),
    ('Let''s Let The Night Begin', 'Original', 1),
    ('Girl, I Wanna Lay You Down', 'ALO / Jack Johnson', 1),
    ('Place To Lay Your Head', 'Frankie Ballard', 1),
    ('Creepin''', 'Eric Church', 1),
    ('Heart Of A Lion', 'Original', 1),
    ('Stray Cat Strut', 'Stray Cats', 1),
    ('Ain''t No Sunshine / Use Me', 'Bill Withers', 1),
    ('I Was On A Boat That Day', 'Old Dominion', 1),
    ('Watermelon Sugar', 'Harry Styles', 1),
    ('Midnight Mess Around', 'Old Dominion', 1),
    ('Nice to Meet You', 'Niall Horan', 1),
    ('I Had Some Help', 'Post Malone, Morgan Wallen', 1)
    ('It Don''t Matter', 'Donovan Frankenreiter', 1),
    ('Breakdown', 'Tom Petty', 1),
    ('Little Wing', 'Stevie Ray Vaughan', 1),
    ('Waves of Passion', 'Original', 1),
    ('Only For You', 'Tomorrows Bad Seeds', 1),
    ('Oooh La La', 'Rod Stewart', 1),
    ('Go', 'Original', 1),
    ('Crazy Little Thing Called Love', 'Queen', 1),
    ('Cuts Like a Knife', 'Bryan Adams', 1),
    ('Your Body Is Wonderland', 'John Mayer', 1),
    ('Ingrid', 'Original', 1),
    ('Good One Coming On', 'Blackberry Smoke', 1),
    ('Mr. Misunderstood', 'Eric Church', 1),
    ('Feathered Indians', 'Tyler Childers', 1),
    ('What I Got', 'Sublime', 1),
    ('I Can''t Go For That', 'Hall & Oates', 1);